spring.application.name=KFPCL_BACKEND_DEV
server.port=8081

spring.datasource.url=jdbc:h2:mem:kfpcl_devdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

aws.s3.bucket=kfpcl-backend-images-2026
aws.s3.region=ap-south-1
